import Arrow from './arrow';
const posts = [{"url": "https://www.instagram.com/p/Dax_0u5FDqj/", "kind": "Post"}, {"url": "https://www.instagram.com/reel/DZfliBpxow4/", "kind": "Post"}, {"url": "https://www.instagram.com/p/DbyB0MZFMKa/", "kind": "Post"}, {"url": "https://www.instagram.com/reel/Da5YZUQjeyt/", "kind": "Post"}, {"url": "https://www.instagram.com/p/DcoGgfIDfI9/", "kind": "Post"}, {"url": "https://www.instagram.com/reel/DcgYSvyjcSu/", "kind": "Post"}, {"url": "https://www.instagram.com/p/DbgAWKBD1hv/", "kind": "Post"}, {"url": "https://www.instagram.com/reel/Dc1jfk3gbMq/", "kind": "Post"}];
export default function SocialCarousel() {
return <section className="chapter social-carousel" id="social-content" aria-labelledby="social-title" aria-roledescription="carousel">
<p className="chapter-label"><span>Activation Social Content</span></p><h2 id="social-title">A clear message. A more visible Stephanie.</h2>
<p className="intro balanced-intro">With a defined message and professional content, Stephanie began showing more of herself online. Women could hear her perspective, understand her coaching, and see the person behind her medical credentials.</p>
<div className="social-carousel-heading"><div className="social-controls"><button type="button" aria-label="Previous Instagram posts" aria-controls="social-posts" data-carousel-direction="-1" disabled><Arrow direction="left"/></button><button type="button" aria-label="Next Instagram posts" aria-controls="social-posts" data-carousel-direction="1"><Arrow direction="right"/></button></div></div>
<ul id="social-posts" className="social-track instagram-track" aria-label="Stephanie’s Instagram posts" tabIndex={0}>{posts.map((post,i)=><li key={post.url} className="social-card instagram-card"><div className="instagram-embed-wrap"><blockquote className="instagram-media" data-instgrm-permalink={post.url} data-instgrm-version="14"><a href={post.url} target="_blank" rel="noopener noreferrer">View {post.kind.toLowerCase()} {i+1} by @stephaniebyerlymd on Instagram</a></blockquote></div><a className="social-card-label instagram-direct-link" href={post.url} target="_blank" rel="noopener noreferrer" aria-label={`Open Stephanie’s Instagram ${post.kind.toLowerCase()} ${i+1} in a new tab`}><span>{post.kind} {String(i+1).padStart(2,'0')} · View on Instagram</span><Arrow/></a></li>)}</ul>
<p className="social-position" aria-live="polite" aria-atomic="true">8 Instagram posts</p>
</section>;
}
